baseURL = 'https://bearxz.github.io/'
# ç½‘ç«™è¯­è¨€, ä»…åœ¨è¿™é‡Œ CN å¤§å†™ ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# è®¾ç½®é»˜è®¤çš„è¯­è¨€ ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "zh-cn"
# æ˜¯å¦åŒ…æ‹¬ä¸­æ—¥éŸ©æ–‡å­—
dateFormat = '2006-01-02'
enablePWA = true
hasCJKLanguage = true
images = ['/assets/logo.ong']
title = 'åäºŒæ¥¼äº”åŸ'
# ä¸»é¢˜
theme = 'FixIt'
publishDir = docs

# ä½œè€…é…ç½®
[author]
avatar = "/author.png" # FixIt 0.2.18 | æ–°å¢
email = "" 
link = "" 
name = "bearxz" 

[menu]

# [[menu.main]]
# identifier = "knowledge"
# name = "çŸ¥è¯†ç½‘ç»œ"
# url = "/knowledge/"
# weight = 1
# [menu.main.params]
# # whether set as a draft menu item whose function is similar to a draft post/page
# draft = false
# # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
# icon = "fa-solid fa-circle-nodes"

# [[menu.main]]
# identifier = "frontend"
# name = "å‰ç«¯"
# parent = "knowledge"
# url = "/knowledge/frontend/"
# weight = 1
# [menu.main.params]
# # whether set as a draft menu item whose function is similar to a draft post/page
# draft = false
# # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
# icon = "fa-brands fa-chrome"

# [[menu.main]]
# identifier = "openharmony"
# name = "OHOS"
# parent = "knowledge"
# url = "/knowledge/openharmony/"
# weight = 2
# [menu.main.params]
# # whether set as a draft menu item whose function is similar to a draft post/page
# draft = false
# # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
# icon = "fa-solid fa-bullseye"

# [[menu.main]]
# identifier = "rust"
# name = "Rust"
# parent = "knowledge"
# url = "/knowledge/rust/"
# weight = 3
# [menu.main.params]
# # whether set as a draft menu item whose function is similar to a draft post/page
# draft = false
# # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
# icon = "fa-brands fa-rust"

[[menu.main]]
identifier = "posts"
name = "çŸ¥è¯†ç½‘ç»œ"
url = "/posts/"
weight = 2
[menu.main.params]
# whether set as a draft menu item whose function is similar to a draft post/page
draft = false
# FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
# icon = "fa-solid fa-archive"
icon = "fa-solid fa-circle-nodes"

[[menu.main]]
identifier = "categories"
name = "åˆ†ç±»"
title = ""
url = "/categories/"
weight = 3
[menu.main.params]
icon = "fa-solid fa-th"

[[menu.main]]
identifier = "tags"
name = "æ ‡ç­¾"
url = "/tags/"
weight = 4
[menu.main.params]
icon = "fa-solid fa-tags"

[[menu.main]]
identifier = "about"
name = "å…³äº"
url = "/about"
weight = 5
[menu.main.params]
icon = "fa-solid fa-mask"

# Hugo è§£ææ–‡æ¡£çš„é…ç½®
[markup]
# è¯­æ³•é«˜äº®è®¾ç½® (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
################## å¿…è¦çš„é…ç½® ##################
# https://github.com/hugo-fixit/FixIt/issues/43
codeFences = true
lineNos = true
lineNumbersInTable = true
noClasses = false
################## å¿…è¦çš„é…ç½® ##################
guessSyntax = true
# Goldmark æ˜¯ Hugo 0.60 ä»¥æ¥çš„é»˜è®¤ Markdown è§£æåº“
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
# æ˜¯å¦åœ¨æ–‡æ¡£ä¸­ç›´æ¥ä½¿ç”¨ HTML æ ‡ç­¾
unsafe = true
# ç›®å½•è®¾ç½®
[markup.tableOfContents]
endLevel = 6
startLevel = 1

[params]
# FixIt 0.2.12 | æ–°å¢ å¼€å¯ PWA æ”¯æŒ
enablePWA = true
# FixIt 0.2.14 | æ–°å¢ æ˜¯å¦è‡ªåŠ¨æ˜¾ç¤ºå¤–é“¾å›¾æ ‡
externalIcon = false
# FixIt 0.2.14 | æ–°å¢ é»˜è®¤æƒ…å†µä¸‹ï¼ŒFixIt åªä¼šåœ¨ä¸»é¡µçš„ HTML å¤´ä¸­æ³¨å…¥ä¸»é¢˜å…ƒæ ‡è®°
# æ‚¨å¯ä»¥å°†å…¶å…³é—­ï¼Œä½†å¦‚æœæ‚¨ä¸è¿™æ ·åšï¼Œæˆ‘ä»¬å°†ä¸èƒœæ„Ÿæ¿€ï¼Œå› ä¸ºè¿™æ˜¯è§‚å¯Ÿ FixIt å—æ¬¢è¿ç¨‹åº¦ä¸Šå‡çš„å¥½æ–¹æ³•
disableThemeInject = true
# ç½‘ç«™æè¿°
description = "è¿™æ˜¯åäºŒæ¥¼äº”åŸçš„ç½‘ç«™"
# ç½‘ç«™å…³é”®è¯
keywords = ["Hugo", "åäºŒæ¥¼äº”åŸ", "bearxz"]

# FixIt 0.2.0 | æ–°å¢ åº”ç”¨å›¾æ ‡é…ç½®
[params.app]
# å½“æ·»åŠ åˆ° iOS ä¸»å±å¹•æˆ–è€… Android å¯åŠ¨å™¨æ—¶çš„æ ‡é¢˜ï¼Œè¦†ç›–é»˜è®¤æ ‡é¢˜
title = "BearXZ"
# æ˜¯å¦éšè—ç½‘ç«™å›¾æ ‡èµ„æºé“¾æ¥
noFavicon = false
# æ›´ç°ä»£çš„ SVG ç½‘ç«™å›¾æ ‡ï¼Œå¯æ›¿ä»£æ—§çš„ .png å’Œ .ico æ–‡ä»¶
svgFavicon = "/logo.svg"
# Safari å›¾æ ‡é¢œè‰²
iconColor = "#5bbad5"
# Windows v8-10 ç£è´´é¢œè‰²
tileColor = "#da532c"
# FixIt 0.2.12 | æ›´æ”¹ Android æµè§ˆå™¨ä¸»é¢˜è‰²
[params.app.themeColor]
dark = "#252627"
light = "#f8f8f8"

# é¡µé¢å¤´éƒ¨å¯¼èˆªæ é…ç½®
[params.header]
# FixIt 0.2.13 | æ›´æ”¹ æ¡Œé¢ç«¯å¯¼èˆªæ æ¨¡å¼ ["sticky", "normal", "auto"]
desktopMode = "sticky"
# FixIt 0.2.13 | æ›´æ”¹ ç§»åŠ¨ç«¯å¯¼èˆªæ æ¨¡å¼ ["sticky", "normal", "auto"]
mobileMode = "auto"
# FixIt 0.2.0 | æ–°å¢ é¡µé¢å¤´éƒ¨å¯¼èˆªæ æ ‡é¢˜é…ç½®
[params.header.title]
# LOGO çš„ URL
logo = "/logo.svg"
# æ ‡é¢˜åç§°
name = "åäºŒæ¥¼äº”åŸ ğŸ»"
# ä½ å¯ä»¥åœ¨åç§°ï¼ˆå…è®¸ HTML æ ¼å¼ï¼‰ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯ï¼Œä¾‹å¦‚å›¾æ ‡
pre = ""
# ä½ å¯ä»¥åœ¨åç§°ï¼ˆå…è®¸ HTML æ ¼å¼ï¼‰ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯ï¼Œä¾‹å¦‚å›¾æ ‡
post = ""
# FixIt 0.2.5 | æ–°å¢ æ˜¯å¦ä¸ºæ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
typeit = false
# FixIt 0.2.12 | æ–°å¢ é¡µé¢å¤´éƒ¨å¯¼èˆªæ å‰¯æ ‡é¢˜é…ç½®
[params.header.subtitle]
# å‰¯æ ‡é¢˜åç§°ï¼Œå·¦ä¸Šè§’å‰¯æ ‡é¢˜
name = ""
# æ˜¯å¦ä¸ºå‰¯æ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
typeit = false

# é¡µé¢åº•éƒ¨ä¿¡æ¯é…ç½®
[params.footer]
enable = true
# FixIt 0.2.17 | æ›´æ”¹ è‡ªå®šä¹‰å†…å®¹ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
# è¿›é˜¶ä½¿ç”¨ï¼Œè§å‚æ•° `params.customFilePath.footer`
custom = ""
# FixIt 0.2.0 | æ–°å¢ æ˜¯å¦æ˜¾ç¤º Hugo å’Œä¸»é¢˜ä¿¡æ¯
hugo = false
# FixIt 0.2.0 | æ–°å¢ æ˜¯å¦æ˜¾ç¤ºç‰ˆæƒä¿¡æ¯
copyright = true
# FixIt 0.2.0 | æ–°å¢ æ˜¯å¦æ˜¾ç¤ºä½œè€…
author = true
# ç½‘ç«™åˆ›ç«‹å¹´ä»½
since = 2023
# FixIt 0.2.14 | æ–°å¢ æ˜¯å¦æ˜¾ç¤ºç½‘ç«™å†…å®¹æ€»å­—æ•°
wordCount = true
# FixIt 0.2.12 | æ–°å¢ å…¬ç½‘å®‰å¤‡ä¿¡æ¯ï¼Œä»…åœ¨ä¸­å›½ä½¿ç”¨ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
gov = ""
# FixIt 0.2.12 | æ›´æ”¹ ICP å¤‡æ¡ˆä¿¡æ¯ï¼Œä»…åœ¨ä¸­å›½ä½¿ç”¨ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
icp = ""
# è®¸å¯åè®®ä¿¡æ¯ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
# FixIt 0.2.17 | æ›´æ”¹ ç½‘ç«™åˆ›ç«‹æ—¶é—´
[params.footer.siteTime]
animate = true 
enable = true 
icon = "fa-solid fa-heartbeat" 
pre = "ğŸ•¦" 
value = "2023-03-04T11:35:33+08:00" # e.g. "2021-12-18T16:15:22+08:00"
# FixIt 0.2.17 | æ–°å¢ é¡µé¢åº•éƒ¨è¡Œæ’åºï¼Œå¯é€‰å€¼ï¼š["first", 0, 1, 2, 3, 4, 5, "last"]
[params.footer.order]
beian = 0
copyright = 0
powered = 0
statistics = 0
visitor = 0

# FixIt 0.2.0 | æ–°å¢ æœç´¢é…ç½®
[params.search]
enable = true
# æœç´¢å¼•æ“çš„ç±»å‹ ["lunr", "algolia", "fuse"]
type = "fuse"
# æ–‡ç« å†…å®¹æœ€é•¿ç´¢å¼•é•¿åº¦
contentLength = 4000
# æœç´¢æ¡†çš„å ä½æç¤ºè¯­
placeholder = ""
# FixIt 0.2.1 | æ–°å¢ æœ€å¤§ç»“æœæ•°ç›®
maxResultLength = 10
# FixIt 0.2.3 | æ–°å¢ ç»“æœå†…å®¹ç‰‡æ®µé•¿åº¦
snippetLength = 50
# FixIt 0.2.1 | æ–°å¢ æœç´¢ç»“æœä¸­é«˜äº®éƒ¨åˆ†çš„ HTML æ ‡ç­¾
highlightTag = "em"
# FixIt 0.2.4 | æ–°å¢ æ˜¯å¦åœ¨æœç´¢ç´¢å¼•ä¸­ä½¿ç”¨åŸºäº baseURL çš„ç»å¯¹è·¯å¾„
absoluteURL = false
[params.search.algolia]
appID = ""
index = ""
searchKey = ""
[params.search.fuse]
# FixIt 0.2.17 | æ–°å¢ https://fusejs.io/api/options.html
distance = 100
findAllMatches = false
ignoreFieldNorm = false
ignoreLocation = false
isCaseSensitive = false
location = 0
minMatchCharLength = 2
threshold = 0.3
useExtendedSearch = false

# ä¸»é¡µé…ç½®
[params.home]
# FixIt 0.2.0 | æ–°å¢ RSS æ–‡ç« æ•°ç›®
rss = 10
# ä¸»é¡µä¸ªäººä¿¡æ¯
[params.home.profile]
enable = true
# Gravatar é‚®ç®±ï¼Œç”¨äºä¼˜å…ˆåœ¨ä¸»é¡µæ˜¾ç¤ºçš„å¤´åƒ
gravatarEmail = ""
# ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
avatarURL = "/author.png"
# FixIt 0.2.17 | æ–°å¢ å¤´åƒèœå•é“¾æ¥çš„ identifier
avatarMenu = "about"
# FixIt 0.2.7 | æ›´æ”¹ ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™æ ‡é¢˜ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
title = "ğŸ»"
# ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜
subtitle = "å¤©ä¸Šç™½ç‰äº¬ï¼ŒåäºŒæ¥¼äº”åŸ"
# æ˜¯å¦ä¸ºå‰¯æ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
typeit = true
# æ˜¯å¦æ˜¾ç¤ºç¤¾äº¤è´¦å·
social = true
# FixIt 0.2.0 | æ–°å¢ å…è´£å£°æ˜ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
disclaimer = ""
# ä¸»é¡µæ–‡ç« åˆ—è¡¨
[params.home.posts]
enable = true
# ä¸»é¡µæ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 6

# FixIt 0.2.16 | æ–°å¢ é˜…è¯»è¿›åº¦æ¡
[params.readingProgress]
enable = true
# å¯ç”¨å€¼ï¼š["left", "right"]
start = "left"
# å¯ç”¨å€¼ï¼š["top", "bottom"]
dark = ""
height = "2px"
light = ""
position = "top"
reversed = false

# FixIt 0.2.17 | æ–°å¢ é¡µé¢åŠ è½½æœŸé—´é¡¶éƒ¨çš„è¿›åº¦æ¡
# æœ‰å…³è¯¦ç»†ä¿¡æ¯ï¼šhttps://github.com/CodeByZach/pace
[params.pace]
enable = false
# æ‰€æœ‰å¯ç”¨é¢œè‰²ï¼š
# ["black", "blue", "green", "orange", "pink", "purple", "red", "silver", "white", "yellow"]
color = "orange"
# æ‰€æœ‰å¯ç”¨ä¸»é¢˜ï¼š
# ["barber-shop", "big-counter", "bounce", "center-atom", "center-circle", "center-radar", "center-simple",
# "corner-indicator", "fill-left", "flash", "flat-top", "loading-bar", "mac-osx", "material", "minimal"]
theme = "minimal"

# FixIt 0.2.14 | æ–°å¢ åœ¨å·¦ä¸Šè§’æˆ–è€…å³ä¸Šè§’æ˜¾ç¤º GitHub å¼€æºé“¾æ¥
[params.githubCorner]
enable = true 
permalink = "https://github.com/bearxz/bearxz.github.io" 
position = "right" # ["left", "right"]
title = "åœ¨ GitHub ä¸ŠæŸ¥çœ‹æºä»£ç " 

# FixIt 0.2.7 | æ–°å¢ Cookie è®¸å¯é…ç½®
[params.cookieconsent]
enable = false
# ç”¨äº Cookie è®¸å¯æ¨ªå¹…çš„æ–‡æœ¬å­—ç¬¦ä¸²
[params.cookieconsent.content]
dismiss = ""
link = ""
message = ""

# FixIt 0.2.12 | æ–°å¢ ä¸è’œå­ç»Ÿè®¡
[params.ibruce]
enable = true
# åœ¨æ–‡ç« ä¸­å¼€å¯
enablePost = true

# FixIt 0.2.12 | æ–°å¢ æ°´å°é…ç½®
# è¯¦ç»†å‚æ•°è§ https://github.com/Lruihao/watermark#readme
[params.watermark]
enable = true
# æ°´å°å†…å®¹ï¼ˆå…è®¸ HTML æ ¼å¼ï¼‰
content = "ğŸ» å¤©ä¸Šç™½ç‰äº¬ï¼ŒåäºŒæ¥¼äº”åŸ ğŸ»"
# æ°´å°é€æ˜åº¦
opacity = 0.1
# æ°´å°çˆ¶èŠ‚ç‚¹
appendTo = ".wrapper>main"
# å•æ°´å°å®½åº¦ å•ä½ï¼špx
width = 250
# å•æ°´å°é«˜åº¦ å•ä½ï¼špx
height = 50
# æ°´å°è¡Œé—´è· å•ä½ï¼špx
rowSpacing = 100
# æ°´å°åˆ—é—´è· å•ä½ï¼špx
colSpacing = 100
# æ°´å°æ—‹è½¬è§’åº¦ å•ä½ï¼šdeg
rotate = 15
# æ°´å°å­—ä½“å¤§å°ï¼Œå•ä½ï¼šrem
fontSize = 0.85
# FixIt 0.2.13 | æ–°å¢ æ°´å°å­—ä½“
fontFamily = "inherit"

# ä¸çŸ¥é“æ˜¯ä»€ä¹ˆç©æ„
# FixIt 0.2.12 | æ–°å¢ ç›˜å¤ä¹‹ç™½é…ç½®
[params.pangu]
# é€‚ç”¨äºä¸­æ–‡å†™ä½œç”¨æˆ·
enable = true 
selector = "article" # FixIt 0.2.17 | æ–°å¢

# FixIt 0.2.16 | æ›´æ”¹ ä½œè€…çš„ç¤¾äº¤ä¿¡æ¯è®¾ç½®
[params.social]
Bilibili = ""
Discord = ""
Email = ""
GitHub = "https://github.com/bearxz"
Phone = ""
RSS = false
Twitter = ""
Zhihu = ""

# FixIt 0.2.0 | æ–°å¢ Sectionï¼ˆæ‰€æœ‰æ–‡ç« ï¼‰é¡µé¢é…ç½®
[params.section]
# section é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 20
# æ—¥æœŸæ ¼å¼ï¼ˆæœˆå’Œæ—¥ï¼‰
dateFormat = "2006-01-02"
# RSS æ–‡ç« æ•°ç›®
rss = 10
# FixIt 0.2.13 | æ–°å¢ æœ€è¿‘æ›´æ–°æ–‡ç« è®¾ç½®
[params.section.recentlyUpdated]
days = 30
enable = true
maxCount = 10
rss = false
# FixIt 0.2.0 | æ–°å¢ Listï¼ˆç›®å½•æˆ–æ ‡ç­¾ï¼‰é¡µé¢é…ç½®
[params.list]
# list é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 20
# æ—¥æœŸæ ¼å¼ï¼ˆæœˆå’Œæ—¥ï¼‰
dateFormat = "2006-01-02"
# RSS æ–‡ç« æ•°ç›®
rss = 10

# FixIt 0.2.0 | æ›´æ”¹ æ–‡ç« é¡µé¢é…ç½®
[params.page]
# FixIt 0.2.18 | æ–°å¢ æ˜¯å¦å¯ç”¨æ–‡ç« ä½œè€…å¤´åƒ
authorAvatar = true
# FixIt 0.2.0 | æ–°å¢ æ˜¯å¦åœ¨ä¸»é¡µéšè—ä¸€ç¯‡æ–‡ç« 
hiddenFromHomePage = false
# FixIt 0.2.0 | æ–°å¢ æ˜¯å¦åœ¨æœç´¢ç»“æœä¸­éšè—ä¸€ç¯‡æ–‡ç« 
hiddenFromSearch = false
# FixIt 0.2.0 | æ–°å¢ æ˜¯å¦ä½¿ç”¨ twemoji
twemoji = true
# æ˜¯å¦ä½¿ç”¨ lightgallery
# FixIt 0.2.18 | æ›´æ”¹ å¦‚æœè®¾ä¸º "force"ï¼Œæ–‡ç« ä¸­çš„å›¾ç‰‡å°†å¼ºåˆ¶æŒ‰ç…§ç”»å»Šå½¢å¼å‘ˆç°
lightgallery = false
# FixIt 0.2.0 | æ–°å¢ æ˜¯å¦ä½¿ç”¨ ruby æ‰©å±•è¯­æ³•
ruby = true
# FixIt 0.2.0 | æ–°å¢ æ˜¯å¦ä½¿ç”¨ fraction æ‰©å±•è¯­æ³•
fraction = true
# FixIt 0.2.0 | æ–°å¢ æ˜¯å¦ä½¿ç”¨ fontawesome æ‰©å±•è¯­æ³•
fontawesome = true
# è®¸å¯åè®®ä¿¡æ¯ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
# æ˜¯å¦åœ¨æ–‡ç« é¡µé¢æ˜¾ç¤ºåŸå§‹ Markdown æ–‡æ¡£é“¾æ¥
linkToMarkdown = false
# FixIt 0.2.4 | æ–°å¢ æ˜¯å¦åœ¨ RSS ä¸­æ˜¾ç¤ºå…¨æ–‡å†…å®¹
rssFullText = false
# FixIt 0.2.13 | æ–°å¢ é¡µé¢æ ·å¼ ["narrow", "normal", "wide", ...]
pageStyle = "normal"
# FixIt 0.2.14 | æ–°å¢ FixIt 0.2.18 | åˆ é™¤ å¼ºåˆ¶ä½¿ç”¨ Gravatar ä½œä¸ºä½œè€…å¤´åƒ
# gravatarForce = true
# FixIt 0.2.17 | æ›´æ”¹ å¼€å¯è‡ªåŠ¨ä¹¦ç­¾æ”¯æŒ
# å¦‚æœä¸º trueï¼Œåˆ™åœ¨å…³é—­é¡µé¢æ—¶ä¿å­˜é˜…è¯»è¿›åº¦
autoBookmark = true
# FixIt 0.2.17 | æ–°å¢ æ˜¯å¦ä½¿ç”¨ å­—æ•°ç»Ÿè®¡
wordCount = true
# FixIt 0.2.17 | æ–°å¢ æ˜¯å¦ä½¿ç”¨ é¢„è®¡é˜…è¯»
readingTime = true
# FixIt 0.2.17 | æ–°å¢ æ–‡ç« ç»“æŸæ ‡å¿—
endFlag = "~~~ ğŸ»ï¼šæ–‡ç« ç»“æŸå•¦ ~~~"
# FixIt 0.2.18 | æ–°å¢ æ˜¯å¦å¼€å¯å³æ—¶é¡µé¢
instantPage = true

# FixIt 0.2.15 | æ–°å¢ è½¬è½½é…ç½®
[params.page.repost]
enable = false
url = ""
# FixIt 0.2.0 | æ–°å¢ ç›®å½•é…ç½®
[params.page.toc]
# æ˜¯å¦ä½¿ç”¨ç›®å½•
enable = true
# FixIt 0.2.9 | æ–°å¢ æ˜¯å¦ä¿æŒä½¿ç”¨æ–‡ç« å‰é¢çš„é™æ€ç›®å½•
keepStatic = false
# æ˜¯å¦ä½¿ä¾§è¾¹ç›®å½•è‡ªåŠ¨æŠ˜å å±•å¼€
auto = false
# FixIt 0.2.13 | æ–°å¢ ç›®å½•ä½ç½® ["left", "right"]
position = "right"
# FixIt 0.2.13 | æ–°å¢ åœ¨æ–‡ç« å¼€å¤´æ˜¾ç¤ºæç¤ºä¿¡æ¯ï¼Œæé†’è¯»è€…æ–‡ç« å†…å®¹å¯èƒ½è¿‡æ—¶
[params.page.expirationReminder]
enable = true
# å¦‚æœæ–‡ç« æœ€åæ›´æ–°äºè¿™å¤©æ•°ä¹‹å‰ï¼Œæ˜¾ç¤ºæé†’
reminder = 90
# å¦‚æœæ–‡ç« æœ€åæ›´æ–°äºè¿™å¤©æ•°ä¹‹å‰ï¼Œæ˜¾ç¤ºè­¦å‘Š
warning = 180
# å¦‚æœæ–‡ç« åˆ°æœŸæ˜¯å¦å…³é—­è¯„è®º
closeComment = false
# FixIt 0.2.0 | æ–°å¢ ä»£ç é…ç½®
[params.page.code]
# æ˜¯å¦æ˜¾ç¤ºä»£ç å—çš„å¤åˆ¶æŒ‰é’®
copy = true
# FixIt 0.2.13 | æ–°å¢ æ˜¯å¦æ˜¾ç¤ºä»£ç å—çš„ç¼–è¾‘æŒ‰é’®
edit = false
# é»˜è®¤å±•å¼€æ˜¾ç¤ºçš„ä»£ç è¡Œæ•°
maxShownLines = 10
# FixIt 0.2.14 | æ–°å¢ æ–‡ç« ç¼–è¾‘
[params.page.edit]
enable = false
# FixIt 0.2.15 | æ›´æ”¹ ç¼–è¾‘çš„åŸºç¡€é“¾æ¥
# url = "/edit/branch-name/subdirectory-name" # ç›¸å¯¹äº `params.gitRepo`
# url = "https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name" # å®Œæ•´é“¾æ¥
url = ""
# FixIt 0.2.0 | æ›´æ”¹ KaTeX æ•°å­¦å…¬å¼ (https://katex.org)
[params.page.math]
enable = true
# é»˜è®¤è¡Œå†…å®šç•Œç¬¦æ˜¯ $ ... $ å’Œ \( ... \)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# é»˜è®¤å—å®šç•Œç¬¦æ˜¯ $$ ... $$, \[ ... \],  \begin{equation} ... \end{equation} å’Œä¸€äº›å…¶å®ƒçš„å‡½æ•°
blockLeftDelimiter = ""
blockRightDelimiter = ""
# KaTeX æ’ä»¶ copy_tex
copyTex = true
# KaTeX æ’ä»¶ mhchem
mhchem = true
# FixIt 0.2.0 | æ–°å¢ Mapbox GL JS é…ç½® (https://docs.mapbox.com/mapbox-gl-js)
[params.page.mapbox]
# Mapbox GL JS çš„ access token
accessToken = ""
# æµ…è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
lightStyle = "mapbox://styles/mapbox/light-v9"
# æ·±è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
darkStyle = "mapbox://styles/mapbox/dark-v9"
# æ˜¯å¦æ·»åŠ  NavigationControl
navigation = true
# æ˜¯å¦æ·»åŠ  GeolocateControl
geolocate = true
# æ˜¯å¦æ·»åŠ  ScaleControl
scale = true
# æ˜¯å¦æ·»åŠ  FullscreenControl
fullscreen = true
# FixIt 0.2.17 | æ–°å¢ èµèµè®¾ç½®
[params.page.reward]
animation = true
enable = false
# ç›¸å¯¹äºé¡µè„šçš„ä½ç½®ï¼Œå¯é€‰å€¼ï¼š["before", "after"]
position = "after"
# comment = "Buy me a coffee"
[params.page.reward.ways]
# wechatpay = "/images/wechatpay.png"
# alipay = "/images/alipay.png"
# paypal = "/images/paypal.png"
# bitcoin = "/images/bitcoin.png"
# FixIt 0.2.0 | æ›´æ”¹ æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
# FixIt 0.2.0 | æ›´æ”¹ æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
[params.page.share]
Baidu = false
Evernote = false
Facebook = false
HackerNews = false
Twitter = false
Weibo = false
Whatsapp = false
enable = false

# FixIt 0.2.15 | æ›´æ”¹
[mediaTypes]
# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[mediaTypes."text/markdown"]
suffixes = ["md"]
# ç”¨äºè¾“å‡º txt æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[mediaTypes."text/plain"]
suffixes = ["txt"]

# FixIt 0.2.15 | æ›´æ”¹
[outputFormats]
# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[outputFormats.MarkDown]
isHTML = false
isPlainText = true
mediaType = "text/markdown"
# FixIt 0.2.15 | æ–°å¢ ç”¨äºè¾“å‡º baidu_urls.txt æ–‡ä»¶çš„è®¾ç½®
[outputFormats.BaiduUrls]
baseName = "baidu_urls"
isHTML = false
isPlainText = true
mediaType = "text/plain"

# FixIt 0.2.15 | æ›´æ”¹ ç”¨äº Hugo è¾“å‡ºæ–‡æ¡£çš„è®¾ç½®
[outputs]
home = ["HTML", "RSS", "JSON", "BaiduUrls"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]
